[phases.setup]
nixPkgs = ["nodejs_22", "python311", "ffmpeg", "fontconfig", "dejavu_fonts"]

[phases.install]
cmds = [
  "cd backend && npm ci --legacy-peer-deps || npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npm start"
